face_detection:
  model_name: "scrfd_10g_bnkps"
  confidence_threshold: 0.5
  nms_threshold: 0.4
  detection_size: 640
  max_faces: 10
  gpu_memory_fraction: 0.6

face_alignment:
  model_name: "2dfan4"
  landmark_detector: "face_alignment"
  align_size: 512
  padding_factor: 0.3
  use_enhancement: true

identity_preservation:
  model_name: "instantid"
  controlnet_model: "InstantX/InstantID"
  adapter_model: "ip-adapter_instant_id_sdxl"
  strength: 0.8
  guidance_scale: 7.5
  num_inference_steps: 20

inference_engine:
  model_name: "inswapper_128"
  face_swapper: "facefusion"
  batch_size: 1
  num_threads: 4
  optimization_level: 3
  precision: "fp16"
  cache_size: 100

frame_interpolation:
  enabled: true
  model_name: "rife_v4.6"
  interpolation_factor: 2
  enhance_quality: true
  use_film_fallback: true

system:
  device: "auto"
  gpu_ids: [0]
  num_workers: 4
  memory_limit: "48GB"
  temp_dir: "/tmp/face_swap_super"
  log_level: "INFO"
  enable_profiling: false

security:
  enable_nsfw_filter: false
  enable_deepfake_detection: false
  watermark_enabled: false
  content_moderation: false
  rate_limiting: true
  max_concurrent_requests: 10

web:
  host: "0.0.0.0"
  port: 8000
  enable_cors: true
  websocket_enabled: true
  max_file_size: "100MB"
  session_timeout: 3600
