name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1️⃣ Set up Buildx with the right driver
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container     # <- crucial
        buildkitd-flags: --debug     # optional, nice for logs

    # 2️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3️⃣ Build & push (cache now works)
    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          beasthavoc/super-faceswap:latest
          beasthavoc/super-faceswap:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
