name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]   # build only when main changes
  workflow_dispatch:        # let you trigger it manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # 1. Check out your repo
    - uses: actions/checkout@v4

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build *and* push
    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # tag as :latest **and** :commit‑sha for traceability
        tags: |
          beasthavoc/super-faceswap:latest
          beasthavoc/super-faceswap:${{ github.sha }}

        # optional: leverage build‑kit cache to speed things up
        cache-from: type=gha
        cache-to: type=gha,mode=max
